repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  #- id: trailing-whitespace 
  #- id: end-of-file-fixer  # add EOF "\n" if missing
  - id: check-merge-conflict
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-added-large-files
    args: ['--maxkb=50'] 
  - id: check-case-conflict
  #- id: check-symlinks
  #- id: check-xml
  - id: check-yaml
    args: [--unsafe]
  - id: detect-private-key
  #- id: pretty-format-json

#- repo: https://github.com/Lucas-C/pre-commit-hooks
#  rev: "v1.5.5"
#  hooks:
#  - id: forbid-tabs

#- repo: https://github.com/cheshirekow/cmake-format-precommit
#  rev: v0.6.10
#  hooks:
#  - id: cmake-format
#  - id: cmake-lint

#- repo: https://github.com/codespell-project/codespell
#  rev: "v2.3.0"
#  hooks:
#  - id: codespell

#- repo: https://github.com/shellcheck-py/shellcheck-py
#  rev: "v0.10.0.1"
#  hooks:
#  - id: shellcheck

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.28.6
  hooks:
  - id: check-github-workflows


# Clang format the codebase automatically
#- repo: https://github.com/pre-commit/mirrors-clang-format
#  rev: "v18.1.8"
#  hooks:
#  - id: clang-format
#    types_or: [c++, c, cuda]

- repo: local
  hooks:
    - id: doxygen_header
      name: "Check doxygen headers"
      entry: python buildbot/check_doxygen_fileheader.py
      language: python
      pass_filenames: false
    - id: license_check
      name: "Check license headers"
      entry: python buildbot/check_licencing.py
      language: python
      pass_filenames: false
    - id: pragma_once_check
      name: "Check #pragma once"
      entry: python buildbot/check_pragma_once.py
      language: python
      pass_filenames: false
    - id: check_sycl_include
      name: "Check SYCL #include"
      entry: python buildbot/check_sycl_include.py
      language: python
      pass_filenames: false