name: DPCPP


on:
  workflow_call:
  workflow_dispatch:
    
jobs:
  nightly_build20230112:
    name: Cache Nightly build 2023-01-12
    runs-on: [self-hosted, raw]
    
    steps:
        
      - name: Cache DPCPP
        id: cache-dpcpp
        uses: actions/cache@v3
        with:
          lookup-only: true
          path: dpcpp_compiler
          key: dpcpp-daily20230815.tar.gz
      
      - name : Download & Untar DPCPP
        if: steps.cache-dpcpp.outputs.cache-hit != 'true'
        run: |
          export DPCPP_URL="https://github.com/intel/llvm/releases/download/nightly-2023-08-15/sycl_linux.tar.gz"
          wget -q --show-progress --progress=bar:force:noscroll "$DPCPP_URL" -O sycl_linux.tar.gz
          echo "untar : "
          tar -xf sycl_linux.tar.gz
          echo "rm archive"
          rm sycl_linux.tar.gz

  cuda_build:

    name: Cache CUDA ${{ matrix.cuda }}
    runs-on: [self-hosted, raw]

    strategy:
      matrix:
        cuda: [12.1.1]
    
    steps:
        
      - name: Cache DPCPP
        id: cache-dpcpp
        uses: actions/cache@v3
        with:
          lookup-only: true
          path: dpcpp_compiler
          key: dpcpp-cuda-${{ matrix.cuda }}.tar.gz

      - name: install latest cmake
        if: steps.cache-dpcpp.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates gpg wget
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
          echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
          sudo apt-get update
          sudo rm /usr/share/keyrings/kitware-archive-keyring.gpg
          sudo apt-get install -y kitware-archive-keyring
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: install CUDA
        if: steps.cache-dpcpp.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/opt/cuda
          wget -q -O cuda.sh https://developer.download.nvidia.com/compute/cuda/12.1.1/local_installers/cuda_12.1.1_530.30.02_linux.run
          sudo sh ./cuda.sh --override --silent --toolkit --no-man-page --no-drm --no-opengl-libs --installpath=~/opt/cuda || true
          echo "CUDA Version ${{matrix.cuda}}" | sudo tee ~/opt/cuda/version.txt
      

      - name: install Ninja-build
        if: steps.cache-dpcpp.outputs.cache-hit != 'true'
        run: sudo apt install ninja-build

      - name: Git clone 
        if: steps.cache-dpcpp.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/intel/llvm -b sycl


      - name: Configure
        if: steps.cache-dpcpp.outputs.cache-hit != 'true'
        run: |
          cd llvm
          CUDA_LIB_PATH=/home/docker/opt/cuda/lib64/stubs python3 buildbot/configure.py \
            --llvm-external-projects compiler-rt \
            --cuda \
            --enable-esimd-emulator \
            --cmake-opt="-DCMAKE_INSTALL_PREFIX=../../dpcpp_compiler" \
            --cmake-opt="-DCUDA_TOOLKIT_ROOT_DIR=/home/docker/opt/cuda"

      - name: Compile
        if: steps.cache-dpcpp.outputs.cache-hit != 'true'
        run: |
          cd llvm/build
          ninja all \
            lib/libsycl-cmath-fp64.o               \
            lib/libsycl-fallback-cstring.spv\
            lib/libsycl-cmath.o                    \
            lib/libsycl-fallback-imf-fp64.o\
            lib/libsycl-complex-fp64.o             \
            lib/libsycl-fallback-imf-fp64.spv\
            lib/libsycl-complex.o                  \
            lib/libsycl-fallback-imf.o\
            lib/libsycl-crt.o                      \
            lib/libsycl-fallback-imf.spv\
            lib/libsycl-fallback-cassert.o         \
            lib/libsycl-imf-fp64.o\
            lib/libsycl-fallback-cassert.spv       \
            lib/libsycl-imf.o\
            lib/libsycl-fallback-cmath-fp64.o      \
            lib/libsycl-itt-compiler-wrappers.o\
            lib/libsycl-fallback-cmath-fp64.spv    \
            lib/libsycl-itt-stubs.o\
            lib/libsycl-fallback-cmath.o           \
            lib/libsycl-itt-user-wrappers.o\
            lib/libsycl-fallback-cmath.spv         \
            lib/libsycl_pi_trace_collector.so\
            lib/libsycl-fallback-complex-fp64.o    \
            lib/libsycl_profiler_collector.so\
            lib/libsycl-fallback-complex-fp64.spv  \
            lib/libsycl_sanitizer_collector.so\
            lib/libsycl-fallback-complex.o         \
            lib/libsycl.so\
            lib/libsycl-fallback-complex.spv       \
            tools/libdevice/libsycldevice\

      - name: Install
        if: steps.cache-dpcpp.outputs.cache-hit != 'true'
        run: |
          cd llvm/build
          ninja install

        

  hip_build:

    name: Cache HIP ROCM ${{ matrix.rocm }}
    runs-on: [self-hosted, raw]

    strategy:
      matrix:
        rocm: [5.4.3]
    
    steps:
        
      - name: Cache DPCPP
        id: cache-dpcpp
        uses: actions/cache@v3
        with:
          lookup-only: true
          path: dpcpp_compiler
          key: dpcpp-hip-${{ matrix.rocm }}.tar.gz

      - name: install latest cmake
        if: steps.cache-dpcpp.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates gpg wget
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
          echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
          sudo apt-get update
          sudo rm /usr/share/keyrings/kitware-archive-keyring.gpg
          sudo apt-get install -y kitware-archive-keyring
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: install ROCm
        if: steps.cache-dpcpp.outputs.cache-hit != 'true'
        run: |
          [[ ${{matrix.rocm}} == 4.0.1 ]] && CODENAME=xenial
          [[ ${{matrix.rocm}} == 5.4.3 ]] && CODENAME=focal
          sudo apt install -y libnuma-dev cmake unzip
          wget -q -O - https://repo.radeon.com/rocm/rocm.gpg.key | sudo apt-key add -
          echo "deb [arch=amd64] https://repo.radeon.com/rocm/apt/${{matrix.rocm}} $CODENAME main" | sudo tee /etc/apt/sources.list.d/rocm.list
          printf 'Package: *\nPin: release o=repo.radeon.com\nPin-Priority: 600' | sudo tee /etc/apt/preferences.d/rocm-pin-600
          sudo apt update -y
          sudo apt install -y rocm-dev

      
      - name: install Ninja-build
        if: steps.cache-dpcpp.outputs.cache-hit != 'true'
        run: sudo apt install ninja-build

      - name: Git clone 
        if: steps.cache-dpcpp.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/intel/llvm -b sycl

      

      
      - name: Configure
        if: steps.cache-dpcpp.outputs.cache-hit != 'true'
        run: |
          cd llvm
          CUDA_LIB_PATH=/home/docker/opt/cuda/lib64/stubs python3 buildbot/configure.py \
            --llvm-external-projects compiler-rt \
            --hip \
            --enable-esimd-emulator \
            --cmake-opt="-DCMAKE_INSTALL_PREFIX=../../dpcpp_compiler" \
            --cmake-opt="-DSYCL_BUILD_PI_HIP_ROCM_DIR=/opt/rocm"

      
      - name: Compile
        if: steps.cache-dpcpp.outputs.cache-hit != 'true'
        run: |
          cd llvm/build
          ninja all \
            lib/libsycl-cmath-fp64.o               \
            lib/libsycl-fallback-cstring.spv\
            lib/libsycl-cmath.o                    \
            lib/libsycl-fallback-imf-fp64.o\
            lib/libsycl-complex-fp64.o             \
            lib/libsycl-fallback-imf-fp64.spv\
            lib/libsycl-complex.o                  \
            lib/libsycl-fallback-imf.o\
            lib/libsycl-crt.o                      \
            lib/libsycl-fallback-imf.spv\
            lib/libsycl-fallback-cassert.o         \
            lib/libsycl-imf-fp64.o\
            lib/libsycl-fallback-cassert.spv       \
            lib/libsycl-imf.o\
            lib/libsycl-fallback-cmath-fp64.o      \
            lib/libsycl-itt-compiler-wrappers.o\
            lib/libsycl-fallback-cmath-fp64.spv    \
            lib/libsycl-itt-stubs.o\
            lib/libsycl-fallback-cmath.o           \
            lib/libsycl-itt-user-wrappers.o\
            lib/libsycl-fallback-cmath.spv         \
            lib/libsycl_pi_trace_collector.so\
            lib/libsycl-fallback-complex-fp64.o    \
            lib/libsycl_profiler_collector.so\
            lib/libsycl-fallback-complex-fp64.spv  \
            lib/libsycl_sanitizer_collector.so\
            lib/libsycl-fallback-complex.o         \
            lib/libsycl.so\
            lib/libsycl-fallback-complex.spv       \
            tools/libdevice/libsycldevice\

      - name: Install
        if: steps.cache-dpcpp.outputs.cache-hit != 'true'
        run: |
          cd llvm/build
          ninja install
        