name: OpenSYCL MacOs pipeline

on:
    workflow_call:
        inputs:
          os:
                required: true
                type: string
      
jobs:
    
    cache_opensycl:
        uses: ./.github/workflows/macos-cache-opensycl.yml
        with:
            os: ${{ inputs.os }}
        secrets: inherit

    shamrock_test_opensycl:
        needs: cache_opensycl
        uses: ./.github/workflows/shamtest-opensycl-macos.yml
        with:
            os: ${{ inputs.os }}
        secrets: inherit