name: Documentation

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_call:


jobs:

  #make shamrock documentation
  make_documentation:
    name: "Build : Documentation"

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: pip install packages (Jupyter book)
        run: pip install -U jupyter-book sphinx_proof matplotlib numpy

      - name: pip install packages (mkdocs)
        run: pip install mkdocs-material mkdocs-git-committers-plugin-2 mkdocs-git-authors-plugin mkdocs-git-revision-date-plugin mkdocs-git-revision-date-localized-plugin

      - name : Install pck (doxygen)
        run: |
          sudo apt-get install -y -qq doxygen graphviz

      - name: Gen doc
        run: |
          cd doc
          sh make_doc.sh

      - name: 'Tar doc'
        run: tar -cvf documentation.tar.gz doc/_build

      - name: Archive generated doc
        uses: actions/upload-artifact@v3
        with:
          name: shamrock_documentation
          path: documentation.tar.gz