name: Pull request checks

# Controls when the workflow will run
on:
  pull_request:


jobs:

  #detect_changes:
  #  name: "Change detect"
  #  uses: ./.github/workflows/detect_changes.yml

  src_check:
    name: "Src checks"
    #needs: [detect_changes]
    uses: ./.github/workflows/source_checks.yml

  
  #make shamrock documentation
  make_documentation:
    name: "Documentation"
    needs: [src_check]
    uses: ./.github/workflows/make_documentation.yml

  shamrock_linux_acpp:
    name: Shamrock Test
    needs: [src_check]
    uses: ./.github/workflows/shamrock-acpp-clang15.yml

  shamrock_linux_acpp_macos:
    name: Shamrock Test
    needs: [src_check]
    if: contains(github.event.pull_request.labels.*.name, 'test-macos')
    uses: ./.github/workflows/shamrock-acpp-macos.yml

  shamrock_linux_acpp_asan:
    name: Shamrock Test
    needs: [src_check]
    uses: ./.github/workflows/shamrock-acpp-clang15-asan.yml

  shamrock_linux_acpp_tidy:
    name: Shamrock Test
    needs: [src_check]
    uses: ./.github/workflows/shamrock-acpp-clang15-tidy.yml

  shamrock_linux_acpp_cov:
    name: Shamrock Test
    needs: [src_check]
    uses: ./.github/workflows/shamrock-acpp-clang15-coverage.yml
    
  shamrock_linux_dpcpp:
    name: Shamrock Test
    needs: [src_check]

    uses: ./.github/workflows/shamrock-dpcpp.yml

  
  shamrock_linux_acpp_phystests:
    name: Shamrock Phys Test
    needs: [shamrock_linux_acpp]
    uses: ./.github/workflows/shamrock-acpp-phys-test.yml
