name: Pull request checks

# Controls when the workflow will run
on:
  pull_request:


jobs:


  src_check:
    name: "Src checks"
    uses: ./.github/workflows/source_checks.yml

  
  #make shamrock documentation
  make_documentation:
    name: "Documentation"
    needs: [src_check]
    uses: ./.github/workflows/make_documentation.yml



  shamrock_linux_acpp:
    name: Shamrock Test
    needs: [src_check]
    uses: ./.github/workflows/shamrock-acpp-clang15.yml

  shamrock_linux_acpp_macos:
    name: Shamrock Test
    needs: [src_check]
    uses: ./.github/workflows/shamrock-acpp-macos.yml

  shamrock_linux_acpp_asan:
    name: Shamrock Test
    needs: [src_check]
    uses: ./.github/workflows/shamrock-acpp-clang15-asan.yml

  shamrock_linux_acpp_cov:
    name: Shamrock Test
    needs: [src_check]
    uses: ./.github/workflows/shamrock-acpp-clang15-coverage.yml
    
  shamrock_linux_dpcpp:
    name: Shamrock Test
    needs: [src_check]

    uses: ./.github/workflows/shamrock-dpcpp.yml