name: Prepare release

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:

  make_documentation:
    name: Doc
    uses: ./.github/workflows/make_documentation.yml

  shamrock_linux_acpp_cov:
    name: Tests
    uses: ./.github/workflows/shamrock-acpp-clang-coverage.yml

  make_code_archive:
    name: Make Code Archive
    uses: ./.github/workflows/make_code_archive.yml
