name: Acpp/clang15


on:
  workflow_call:
  
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    # At 02:00 on Monday, Wednesday, and Friday.
    - cron:  '0 2 * * 1,3,5'

jobs:


  shamrock_acpp:
    name: AdaptiveCpp ${{ matrix.profile }} clang-${{ matrix.clang }}
    runs-on: [self-hosted, ubuntu20]

    strategy:
      matrix:
        include: 
          - clang: 15
            cuda: 11.0.2
            rocm: 5.4.3
            backend: omp
            arch: 
    #if: false
  
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
  
      - name: ls local
        run : ls -la

      - name: Setup env
        run : ./env/new-env --machine debian-generic.acpp --builddir build -- --backend ${{ matrix.backend }} --arch ${{ matrix.arch }}
  
      - name: Configure
        run: |
          cd build
          source activate && shamconfigure

      - name: Build
        run: |
          cd build
          source activate && shamconfigure

      - name: Pull reference files
        run: |
          cd build
          git clone https://github.com/Shamrock-code/reference-files.git

  
      - name: run Shamrock Unittests world_size = 1
        run: |
          cd build
          ./shamrock_test --sycl-ls-map  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi
  
      - name: run Shamrock Unittests world_size = 2
        run: |
          cd build
          mpirun -n 2 ./shamrock_test --sycl-ls-map  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi
      
      - name: run Shamrock Unittests world_size = 3
        run: |
          cd build
          mpirun --oversubscribe -n 3 ./shamrock_test --sycl-ls-map  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi
  
      - name: run Shamrock Unittests world_size = 4
        run: |
          cd build
          mpirun --oversubscribe -n 4 ./shamrock_test --sycl-ls-map  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi
