name: Acpp/ Apple clang (Macos)


on:
  workflow_call:
  
  #push:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  #schedule:
  #  # At 02:00 on Monday, Wednesday, and Friday.
  #  - cron:  '0 2 * * 1,3,5'

jobs:


  shamrock_acpp:
    name: AdaptiveCpp macos
    runs-on: macos-latest
  
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
  
      - name: ls local
        run : ls -la

      - name: install dependencies
        run: |
          set +e
          brew update
          brew install cmake
          brew install libomp
          brew install boost
          brew install openmpi
          set -e

      - name: Setup env
        run : ./env/new-env --machine macos-generic.acpp --builddir build -- 
  
      - uses: ./.github/workflows/actions/shamrock_test.yml