name: Acpp/clang15 (UBsan)


on:
  workflow_call:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  shamrock_acpp_omp_ubsan:
    name: AdaptiveCpp omp ubsan clang-${{ matrix.clang }}
    runs-on: [self-hosted,  docker-runner]

    container:
      image: ${{ matrix.container }}

    if: false

    strategy:
      matrix:
        include: 
          - clang: 15
            cuda: 11.0.2
            rocm: 5.4.3
            container: ghcr.io/shamrock-code/ci-ubuntu20:main
    #if: false
  
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
  
      - name: ls local
        run : ls -la
      
      - name: install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh ${{matrix.clang}}
          sudo apt install -y libclang-${{matrix.clang}}-dev clang-tools-${{matrix.clang}} libomp-${{matrix.clang}}-dev
          if [[ "${{matrix.clang}}" == "16" ]]; then
            sudo rm -r /usr/lib/clang/16*
            sudo ln -s /usr/lib/llvm-16/lib/clang/16 /usr/lib/clang/16
          fi
          

      - name: configure Shamrock
        run: |
          ./env/new-env --machine debian-generic.acpp --builddir build --type ubsan -- --backend omp
  
      - name: Configure
        shell: bash # In docker container github action default to sh
        run: |
          cd build
          source activate && shamconfigure

      - name: Build
        shell: bash # In docker container github action default to sh
        run: |
          cd build
          source activate && shammake

      - name: Pull reference files
        run: |
          cd build
          git clone https://github.com/Shamrock-code/reference-files.git
  
      - name: run Shamrock Unittests world_size = 1
        run: |
          cd build
          ACPP_VISIBILITY_MASK=omp UBSAN_OPTIONS="halt_on_error=1:print_stacktrace=1" ./shamrock_test --sycl-ls-map  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi
  
      - name: run Shamrock Unittests world_size = 2
        run: |
          cd build
          ACPP_VISIBILITY_MASK=omp UBSAN_OPTIONS="halt_on_error=1:print_stacktrace=1" mpirun -n 2 ./shamrock_test --sycl-ls-map  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi
      
      - name: run Shamrock Unittests world_size = 3
        run: |
          cd build
          ACPP_VISIBILITY_MASK=omp UBSAN_OPTIONS="halt_on_error=1:print_stacktrace=1" mpirun --oversubscribe -n 3 ./shamrock_test --sycl-ls-map  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi
  
      - name: run Shamrock Unittests world_size = 4
        run: |
          cd build
          ACPP_VISIBILITY_MASK=omp UBSAN_OPTIONS="halt_on_error=1:print_stacktrace=1" mpirun --oversubscribe -n 4 ./shamrock_test --sycl-ls-map  --sycl-cfg 0:0 --loglevel 0 --benchmark-mpi

