name: Acpp/clang15

on:
  workflow_call:

jobs:


  shamrock_acpp:
    name: test ${{ matrix.testfile }} AdaptiveCpp clang-${{ matrix.clang }} ${{ matrix.backend }}:${{matrix.arch}} 
    runs-on: [self-hosted, ubuntu20]

    strategy:
      matrix:
        include: 
          - clang: 15
            cuda: 11.0.2
            rocm: 5.4.3
            backend: omp
            arch: none
            runtest: yes
            testfile: sod_tube.py


    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
  
      - name: ls local
        run : ls -la

      - name: Setup env
        run : ./env/new-env --machine debian-generic.acpp --builddir build -- --backend ${{ matrix.backend }} --arch ${{ matrix.arch }}
  
      - name: Configure
        run: |
          cd build
          source activate && shamconfigure

      - name: Build
        run: |
          cd build
          source activate && shammake

      - name: run test
        run: |
          cd build
          ./shamrock --sycl-cfg 0:0 --loglevel 1 --rscript ../exemples/ci_tests/${{ matrix.testfile }}