name: Acpp/clang15


on:
  workflow_call:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:


  shamrock_acpp:
    name: AdaptiveCpp clang-${{ matrix.clang }} ${{ matrix.backend }}:${{matrix.arch}} 
    runs-on: [self-hosted, ubuntu20]

    strategy:
      matrix:
        include: 
          - clang: 15
            cuda: 11.0.2
            rocm: 5.4.3
            backend: omp
            arch: none
            runtest: yes
            uploadartifact: yes
          - clang: 15
            cuda: 11.0.2
            rocm: 5.4.3
            backend: generic
            arch: none
            runtest: yes
          - clang: 15
            cuda: 11.0.2
            rocm: 5.4.3
            backend: cuda.explicit-multipass
            arch: sm_80
          - clang: 15
            cuda: 11.0.2
            rocm: 5.4.3
            backend: cuda.integrated-multipass
            arch: sm_80
          - clang: 15
            cuda: 11.0.2
            rocm: 5.4.3
            backend: hip
            arch: gfx906
  
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
  
      - name: ls local
        run : ls -la

      - name: Setup env
        run : ./env/new-env --machine debian-generic.acpp --builddir build -- --backend ${{ matrix.backend }} --arch ${{ matrix.arch }}
  
      - uses: ./.github/workflows/actions/shamrock_test.yml