name: Acpp/clang

on:
  workflow_call:

jobs:

  build_docker:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Container
        uses: docker/build-push-action@v6
        with:
          tags: ci-phys-test-image
          file: .github/dockerfiles/phys_test_image_acpp_omp/Dockerfile
          context: .
          push: false
          outputs: type=docker,dest=/tmp/ci-phys-test-image.tar
          build-args: |
            CLANGVERSION=18

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ci-phys-test-image
          path: /tmp/ci-phys-test-image.tar

  shamrock_phys_test:
    name: run ${{ matrix.testfile }} wz=${{ matrix.worldsize }} AdaptiveCpp clang-${{ matrix.clang }} ${{ matrix.backend }}:${{matrix.arch}}
    runs-on: ubuntu-latest
    needs: [ build_docker ]

    strategy:
      matrix:
        include:
          - worldsize: 1
            testfile: sod_tube_sph.py
          - worldsize: 1
            testfile: sod_tube_godunov.py
          - worldsize: 2
            testfile: sod_tube_godunov.py
          - worldsize: 1
            testfile: sod_tube_zeus.py
          - worldsize: 2
            testfile: sod_tube_zeus.py
          - worldsize: 1
            testfile: reload_old_dump.py


    timeout-minutes: 60
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ci-phys-test-image
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/ci-phys-test-image.tar

      - name: run test
        uses: addnab/docker-run-action@v3
        with:
          image: ci-phys-test-image
          run: |
            mpirun -report-bindings --allow-run-as-root --bind-to socket:overload-allowed \
                --oversubscribe \
                -n ${{matrix.worldsize}} \
                shamrock \
                --sycl-cfg 0:0 \
                --loglevel 1 \
                --rscript /opt/Shamrock_src/exemples/ci_tests/${{ matrix.testfile }}


  remove-image:
    name: Remove image
    if: always()
    runs-on: ubuntu-latest
    needs: [ build_docker , shamrock_phys_test]
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: ci-phys-test-image


  shamrock_acpp:
    name: run ${{ matrix.testfile }} wz=${{ matrix.worldsize }} AdaptiveCpp clang-${{ matrix.clang }} ${{ matrix.backend }}:${{matrix.arch}}
    runs-on: ubuntu-latest

    container:
      image: ${{ matrix.container }}

    strategy:
      matrix:
        include:
          - clang: 15
            backend: omp
            arch: none
            worldsize: 1
            testfile: sod_tube_sph.py
            container: ghcr.io/shamrock-code/shamrock-ci:ubuntu20
          - clang: 15
            backend: omp
            arch: none
            worldsize: 1
            testfile: sod_tube_godunov.py
            container: ghcr.io/shamrock-code/shamrock-ci:ubuntu20
          - clang: 15
            backend: omp
            arch: none
            worldsize: 2
            testfile: sod_tube_godunov.py
            container: ghcr.io/shamrock-code/shamrock-ci:ubuntu20
          - clang: 15
            backend: omp
            arch: none
            worldsize: 1
            testfile: sod_tube_zeus.py
            container: ghcr.io/shamrock-code/shamrock-ci:ubuntu20
          - clang: 15
            backend: omp
            arch: none
            worldsize: 2
            testfile: sod_tube_zeus.py
            container: ghcr.io/shamrock-code/shamrock-ci:ubuntu20
          - clang: 15
            backend: omp
            arch: none
            worldsize: 1
            testfile: reload_old_dump.py
            container: ghcr.io/shamrock-code/shamrock-ci:ubuntu20
          - clang: 15
            backend: omp
            arch: none
            worldsize: 1
            testfile: dustybox_godunov.py
            container: ghcr.io/shamrock-code/shamrock-ci:ubuntu20
          - clang: 15
            backend: omp
            arch: none
            worldsize: 1
            testfile: dustywave_godunov.py
            container: ghcr.io/shamrock-code/shamrock-ci:ubuntu20


    timeout-minutes: 60
    steps:
      #### Checkout part ####
      # Checkout merge commit if PR otherwise default
      - name : Reconfigure git
        run:  |
          git config --global --add safe.directory '*'
          git config --global --list
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request_target'
        with:
          fetch-depth: 0
          submodules: recursive
          ref: "refs/pull/${{ github.event.number }}/merge"

      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request_target'
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Show diff against main
        if: github.event_name == 'pull_request_target'
        run: git diff ${{ github.event.pull_request.base.sha }} HEAD
      #### End Checkout part ####

      - name: ls local
        run : ls -la

      - name: install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh ${{matrix.clang}}
          sudo apt install -y libclang-${{matrix.clang}}-dev clang-tools-${{matrix.clang}} libomp-${{matrix.clang}}-dev
          if [[ "${{matrix.clang}}" == "16" ]]; then
            sudo rm -r /usr/lib/clang/16*
            sudo ln -s /usr/lib/llvm-16/lib/clang/16 /usr/lib/clang/16
          fi

      - name: install python packages
        run: |
          pip install matplotlib numpy scipy

      - name: Setup env
        run : ./env/new-env --machine debian-generic.acpp --builddir build -- --backend ${{ matrix.backend }} --arch ${{ matrix.arch }}

      - name: Configure
        shell: bash # In docker container github action default to sh
        run: |
          cd build
          source ./activate && shamconfigure

      - name: Build
        shell: bash # In docker container github action default to sh
        run: |
          cd build
          source ./activate && shammake shamrock

      - name: Pull refs
        shell: bash # In docker container github action default to sh
        run: |
          cd build
          source ./activate && pull_reffiles

      - name: run test
        run: |
          cd build
          mpirun -report-bindings --allow-run-as-root --bind-to socket:overload-allowed --oversubscribe -n ${{matrix.worldsize}} ./shamrock --sycl-cfg 0:0 --loglevel 1 --rscript ../exemples/ci_tests/${{ matrix.testfile }}
